# Generated by Django 3.2.9 on 2021-12-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyappUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('addtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'myapp_users',
                'managed': False,
            },
        ),
    ]
